CORE-7704: Update sample code to v3
IDme/python-sample-code pull request #2
Opened 2017-06-30 15:57 UTC by antspriggs

2017-06-30 16:49 UTC, tonycchung commented
i think how the response is parsed needs to be updated as well

2017-06-30 18:41 UTC, tonycchung commented
add a CHANGELOG.md and should be good

2017-07-12 14:18 UTC, tonycchung approved these changes

2017-07-21 12:26 UTC, zachallett requested changes

2017-07-21 12:26 UTC, zachallett commented on templates/index.html
> +  <a href="https://api.id.me/oauth/authorize?client_id=aeab0d4282e2127f900075d9673aeca5&redirect_uri=http://localhost:5000/callback&response_type=code&scope=military" class="idme-btn">
which client credentials are those?

2017-07-21 12:29 UTC, antspriggs commented on templates/index.html
> +  <a href="https://api.id.me/oauth/authorize?client_id=aeab0d4282e2127f900075d9673aeca5&redirect_uri=http://localhost:5000/callback&response_type=code&scope=military" class="idme-btn">
Not sure. Is there a way I can search that in admin?

2017-07-21 12:30 UTC, zachallett commented on templates/index.html
> +  <a href="https://api.id.me/oauth/authorize?client_id=aeab0d4282e2127f900075d9673aeca5&redirect_uri=http://localhost:5000/callback&response_type=code&scope=military" class="idme-btn">
In that case, we should remove it with instructions on how to add their own client credentials

2017-07-21 15:26 UTC, zachallett approved these changes

2017-07-21 15:26 UTC, merged